const hbSemanticTokens = Object.freeze({
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", "PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", sans-serif',
  compactFontSize: 12,
  shell: '#eef0f3',
  shellSoft: '#1a2837',
  shellMuted: '#bdc9d5',
  surfaceWarm: '#fbfcfc',
  borderStrong: '#bfc6ce',
  controlBorder: '#83909c',
  focusColor: 'rgba(0, 103, 197, 0.82)',
  focusRing: '0 0 0 3px rgba(0, 103, 197, 0.18)',
  warningText: '#824f0c',
  warningBorder: '#d6b66d',
  warningSoft: '#fff6e7',
  warningSubtle: '#fffbf2',
  errorText: '#98353a',
  successText: '#246147',
  successSoft: '#edf7f1',
  neutralSoft: '#f4f6f8',
  overlaySoft: 'rgba(255, 255, 255, 0.82)',
  tableRowHover: '#f5f7f9',
  shadowPanel: '0 7px 18px rgba(29, 39, 51, 0.10)',
  grade: Object.freeze({
    S: Object.freeze({ bg: '#253347', fg: '#ffffff' }),
    A: Object.freeze({ bg: '#f3eef6', fg: '#584675' }),
    B: Object.freeze({ bg: '#edf2f4', fg: '#435f71' }),
    C: Object.freeze({ bg: '#f5f0ea', fg: '#725942' }),
    D: Object.freeze({ bg: '#eef0f2', fg: '#4e5a66' }),
  }),
  unratedGrade: Object.freeze({ bg: '#ffffff', fg: '#34414e', border: '#83909c' }),
});

export const themeConfig = {
  token: {
    colorPrimary: '#0067c5',
    colorPrimaryHover: '#0058aa',
    colorPrimaryActive: '#004b91',
    colorPrimaryBg: '#eef6ff',
    colorPrimaryBgHover: '#e4f0fd',
    colorPrimaryBorder: '#a9c9e8',
    colorPrimaryBorderHover: '#76a9d8',
    colorInfo: '#0067c5',
    colorSuccess: '#2f7458',
    colorWarning: '#9b6319',
    colorError: '#b13f43',
    colorErrorHover: '#9e373b',
    colorErrorActive: '#882f33',
    colorErrorBg: '#fff1f1',
    colorErrorBorder: '#ebc1c3',
    colorLink: '#0067c5',
    colorTextBase: '#1d2733',
    colorText: '#1d2733',
    colorTextSecondary: '#4b5866',
    colorTextTertiary: '#5d6976',
    colorTextQuaternary: '#5d6976',
    colorTextDisabled: '#7a8792',
    colorTextPlaceholder: '#5d6976',
    colorBgBase: '#ffffff',
    colorBgLayout: '#f5f6f8',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgContainerDisabled: '#eef1f3',
    colorFill: 'rgba(29, 39, 51, 0.08)',
    colorFillSecondary: 'rgba(29, 39, 51, 0.055)',
    colorFillTertiary: 'rgba(29, 39, 51, 0.035)',
    colorFillQuaternary: 'rgba(29, 39, 51, 0.022)',
    colorBorder: '#d7dce2',
    colorBorderSecondary: '#e7eaee',
    borderRadius: 7,
    borderRadiusLG: 10,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    controlHeight: 34,
    controlHeightSM: 30,
    controlHeightLG: 38,
    controlPaddingHorizontal: 12,
    controlOutline: 'rgba(0, 103, 197, 0.18)',
    controlOutlineWidth: 3,
    controlItemBgHover: '#f2f4f7',
    controlItemBgActive: '#e4f0fd',
    controlItemBgActiveHover: '#d8e9fb',
    fontFamily: hbSemanticTokens.fontFamily,
    fontSize: 15,
    fontSizeSM: 13,
    fontSizeHeading1: 28,
    fontSizeHeading2: 21,
    fontSizeHeading3: 17,
    fontSizeHeading4: 15,
    fontSizeHeading5: 13,
    fontWeightStrong: 600,
    lineHeight: 1.5,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.3,
    lineHeightHeading3: 1.4,
    lineHeightHeading4: 1.45,
    lineHeightHeading5: 1.5,
    boxShadow: '0 12px 30px rgba(29, 39, 51, 0.13)',
    boxShadowSecondary: '0 6px 16px rgba(29, 39, 51, 0.09)',
    boxShadowTertiary: '0 1px 2px rgba(29, 39, 51, 0.05)',
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      siderBg: hbSemanticTokens.shell,
      bodyBg: '#f5f6f8',
    },
    Button: {
      fontWeight: 500,
      defaultBg: '#ffffff',
      defaultColor: '#293542',
      defaultBorderColor: hbSemanticTokens.controlBorder,
      defaultHoverBg: '#f4f6f8',
      defaultHoverColor: '#1d2733',
      defaultHoverBorderColor: '#5f6c79',
      defaultActiveBg: '#e9edf1',
      defaultActiveColor: '#1d2733',
      defaultActiveBorderColor: '#4b5866',
      primaryColor: '#ffffff',
      defaultShadow: '0 1px 1px rgba(29, 39, 51, 0.04)',
      primaryShadow: '0 1px 1px rgba(0, 57, 112, 0.16)',
      dangerShadow: '0 1px 2px rgba(136, 47, 51, 0.16)',
      groupBorderColor: hbSemanticTokens.controlBorder,
      textHoverBg: 'rgba(29, 39, 51, 0.05)',
      linkHoverBg: 'rgba(0, 103, 197, 0.08)',
      borderColorDisabled: '#d7dce2',
      iconGap: 7,
      contentFontSizeSM: 13,
      onlyIconSize: 15,
      onlyIconSizeSM: 14,
      paddingInline: 12,
      paddingInlineSM: 9,
      paddingInlineLG: 14,
    },
    Input: {
      colorBorder: hbSemanticTokens.controlBorder,
      hoverBorderColor: '#0067c5',
      activeBorderColor: '#0067c5',
      activeShadow: '0 0 0 3px rgba(0, 103, 197, 0.14)',
      errorActiveShadow: '0 0 0 3px rgba(177, 63, 67, 0.11)',
      warningActiveShadow: '0 0 0 3px rgba(155, 99, 25, 0.12)',
      addonBg: '#f2f4f6',
      hoverBg: '#ffffff',
      activeBg: '#ffffff',
      paddingInline: 11,
      paddingInlineSM: 9,
      paddingInlineLG: 12,
      paddingBlock: 4,
      paddingBlockSM: 2,
      paddingBlockLG: 6,
      inputFontSize: 14,
      inputFontSizeSM: 13,
      inputFontSizeLG: 14,
    },
    Select: {
      colorBorder: hbSemanticTokens.controlBorder,
      selectorBg: '#ffffff',
      hoverBorderColor: '#0067c5',
      activeBorderColor: '#0067c5',
      activeOutlineColor: 'rgba(0, 103, 197, 0.14)',
      optionSelectedBg: '#e4f0fd',
      optionActiveBg: '#f2f4f7',
      optionSelectedColor: '#004b91',
      optionSelectedFontWeight: 600,
      optionHeight: 34,
      optionPadding: '6px 10px',
      optionFontSize: 13,
      optionLineHeight: 1.45,
      showArrowPaddingInlineEnd: 28,
      clearBg: '#ffffff',
    },
    Card: {
      borderRadiusLG: 9,
      headerBg: 'transparent',
      actionsBg: '#ffffff',
      bodyPadding: 16,
      bodyPaddingSM: 12,
      headerPadding: 16,
      headerPaddingSM: 12,
      headerHeight: 46,
      headerHeightSM: 38,
      headerFontSize: 15,
      headerFontSizeSM: 14,
      extraColor: '#4b5866',
    },
    Table: {
      headerBg: '#f4f5f7',
      headerColor: '#34414e',
      headerSortActiveBg: '#e9edf1',
      headerSortHoverBg: '#e9edf1',
      headerSplitColor: '#e2e6ea',
      borderColor: '#e2e6ea',
      rowHoverBg: '#f5f7f9',
      rowSelectedBg: '#e4f0fd',
      rowSelectedHoverBg: '#d8e9fb',
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      cellPaddingBlockMD: 9,
      cellPaddingInlineMD: 10,
      cellPaddingBlockSM: 7,
      cellPaddingInlineSM: 8,
      headerBorderRadius: 8,
    },
    Tabs: {
      inkBarColor: '#0067c5',
      itemColor: '#4b5866',
      itemHoverColor: '#0058aa',
      itemActiveColor: '#004b91',
      itemSelectedColor: '#004b91',
      titleFontSize: 14,
      horizontalItemGutter: 18,
      horizontalItemPadding: '8px 0',
      horizontalMargin: '0 0 12px 0',
    },
    Menu: {
      dropdownWidth: 238,
      itemBg: 'transparent',
      popupBg: '#ffffff',
      groupTitleColor: '#5d6976',
      groupTitleFontSize: 12,
      groupTitleLineHeight: 1.5,
      itemHoverBg: '#f2f4f7',
      itemSelectedBg: '#e4f0fd',
      itemSelectedColor: '#004b91',
      itemDisabledColor: '#7a8792',
      itemActiveBg: '#eef6ff',
      dangerItemColor: '#b13f43',
      dangerItemHoverColor: '#9e373b',
      dangerItemActiveBg: '#fff1f1',
      dangerItemSelectedColor: '#9e373b',
      dangerItemSelectedBg: '#fff1f1',
      itemBorderRadius: 7,
      itemHeight: 36,
      itemMarginBlock: 2,
      itemPaddingInline: 10,
      iconMarginInlineEnd: 8,
      iconSize: 14,
      fontSize: 13,
    },
    Tag: {
      borderRadiusSM: 5,
      defaultBg: '#f1f3f4',
      defaultColor: '#4b5866',
    },
    Alert: {
      borderRadiusLG: 9,
      defaultPadding: '8px 12px',
      withDescriptionPadding: '14px 16px',
    },
    Modal: {
      borderRadiusLG: 12,
      headerBg: '#ffffff',
      contentBg: '#ffffff',
      titleColor: '#1d2733',
      titleFontSize: 16,
    },
    Drawer: {
      colorBgElevated: '#ffffff',
    },
    Form: {
      labelColor: '#34414e',
      labelFontSize: 13,
      labelHeight: 30,
      itemMarginBottom: 16,
    },
    Segmented: {
      itemSelectedBg: '#ffffff',
      itemSelectedColor: '#004b91',
      itemHoverBg: 'rgba(255, 255, 255, 0.8)',
      itemHoverColor: '#293542',
      trackBg: '#eceff2',
      trackPadding: 3,
    },
    Pagination: {
      itemBg: 'transparent',
      itemActiveBg: '#eef6ff',
      itemActiveColor: '#004b91',
      itemActiveColorHover: '#0058aa',
      itemLinkBg: 'transparent',
      itemSizeSM: 30,
      itemInputBg: '#ffffff',
    },
    Skeleton: {
      gradientFromColor: 'rgba(29, 39, 51, 0.07)',
      gradientToColor: 'rgba(29, 39, 51, 0.14)',
      blockRadius: 6,
      paragraphLiHeight: 12,
      titleHeight: 15,
    },
  },
};

const px = (value) => `${value}px`;

// CSS consumes the same runtime values as ConfigProvider. Feature styles may
// introduce local aliases, but they must not redefine the semantic palette.
export const HB_CSS_VARIABLES = Object.freeze({
  '--hb-bg': themeConfig.token.colorBgLayout,
  '--hb-shell': hbSemanticTokens.shell,
  '--hb-shell-soft': hbSemanticTokens.shellSoft,
  '--hb-shell-muted': hbSemanticTokens.shellMuted,
  '--hb-surface': themeConfig.token.colorBgContainer,
  '--hb-surface-soft': themeConfig.components.Table.headerBg,
  '--hb-surface-warm': hbSemanticTokens.surfaceWarm,
  '--hb-border': themeConfig.token.colorBorder,
  '--hb-border-strong': hbSemanticTokens.borderStrong,
  '--hb-control-border': hbSemanticTokens.controlBorder,
  '--hb-text': themeConfig.token.colorText,
  '--hb-muted': themeConfig.token.colorTextSecondary,
  '--hb-faint': themeConfig.token.colorTextTertiary,
  '--hb-primary': themeConfig.token.colorPrimary,
  '--hb-primary-hover': themeConfig.token.colorPrimaryHover,
  '--hb-primary-active': themeConfig.token.colorPrimaryActive,
  '--hb-primary-dark': themeConfig.token.colorPrimaryActive,
  '--hb-primary-border': themeConfig.token.colorPrimaryBorderHover,
  '--hb-primary-border-subtle': themeConfig.token.colorPrimaryBorder,
  '--hb-primary-soft': themeConfig.token.colorPrimaryBgHover,
  '--hb-primary-subtle': themeConfig.token.colorPrimaryBg,
  '--hb-blue': themeConfig.token.colorInfo,
  '--hb-blue-text': themeConfig.token.colorPrimaryHover,
  '--hb-blue-soft': themeConfig.token.colorPrimaryBgHover,
  '--hb-blue-subtle': themeConfig.token.colorPrimaryBg,
  '--hb-warning': themeConfig.token.colorWarning,
  '--hb-warning-text': hbSemanticTokens.warningText,
  '--hb-warning-border': hbSemanticTokens.warningBorder,
  '--hb-warning-soft': hbSemanticTokens.warningSoft,
  '--hb-warning-subtle': hbSemanticTokens.warningSubtle,
  '--hb-error': themeConfig.token.colorError,
  '--hb-error-text': hbSemanticTokens.errorText,
  '--hb-error-soft': themeConfig.token.colorErrorBg,
  '--hb-error-border': themeConfig.token.colorErrorBorder,
  '--hb-success': themeConfig.token.colorSuccess,
  '--hb-success-text': hbSemanticTokens.successText,
  '--hb-success-soft': hbSemanticTokens.successSoft,
  '--hb-neutral-soft': hbSemanticTokens.neutralSoft,
  '--hb-overlay-soft': hbSemanticTokens.overlaySoft,
  '--hb-font-family': hbSemanticTokens.fontFamily,
  '--hb-type-compact': px(hbSemanticTokens.compactFontSize),
  '--hb-radius': px(themeConfig.token.borderRadius),
  '--hb-radius-sm': px(themeConfig.token.borderRadiusSM),
  '--hb-radius-xs': px(themeConfig.token.borderRadiusXS),
  '--hb-control-height': px(themeConfig.token.controlHeight),
  '--hb-control-height-sm': px(themeConfig.token.controlHeightSM),
  '--hb-control-bg': themeConfig.token.colorBgContainer,
  '--hb-control-hover-bg': themeConfig.token.colorPrimaryBg,
  '--hb-control-active-bg': themeConfig.token.colorPrimaryBgHover,
  '--hb-control-item-hover-bg': themeConfig.token.controlItemBgHover,
  '--hb-table-header-bg': themeConfig.components.Table.headerBg,
  '--hb-table-row-hover-bg': hbSemanticTokens.tableRowHover,
  '--hb-focus-ring': hbSemanticTokens.focusRing,
  '--hb-shadow-soft': themeConfig.token.boxShadowTertiary,
  '--hb-shadow-card': 'none',
  '--hb-shadow-panel': hbSemanticTokens.shadowPanel,
  '--hb-shadow-popover': themeConfig.token.boxShadow,
  '--hb-type-caption': px(themeConfig.token.fontSizeSM),
  '--hb-type-body': px(themeConfig.token.fontSize),
  '--hb-type-section': px(themeConfig.token.fontSizeHeading3),
  '--hb-type-title': px(themeConfig.token.fontSizeHeading2),
  '--hb-type-display': px(themeConfig.token.fontSizeHeading1),
  '--hb-v2-canvas': themeConfig.token.colorBgLayout,
  '--hb-v2-surface': themeConfig.token.colorBgContainer,
  '--hb-v2-surface-muted': themeConfig.components.Table.headerBg,
  '--hb-v2-ink': themeConfig.token.colorText,
  '--hb-v2-ink-secondary': themeConfig.token.colorTextSecondary,
  '--hb-v2-ink-muted': themeConfig.token.colorTextTertiary,
  '--hb-v2-stroke': themeConfig.token.colorBorder,
  '--hb-v2-stroke-strong': hbSemanticTokens.borderStrong,
  '--hb-v2-stroke-subtle': themeConfig.token.colorBorderSecondary,
  '--hb-v2-control-border': hbSemanticTokens.controlBorder,
  '--hb-v2-brand': themeConfig.token.colorPrimary,
  '--hb-v2-brand-hover': themeConfig.token.colorPrimaryHover,
  '--hb-v2-brand-active': themeConfig.token.colorPrimaryActive,
  '--hb-v2-brand-border': themeConfig.token.colorPrimary,
  '--hb-v2-brand-wash': themeConfig.token.colorPrimaryBgHover,
  '--hb-v2-brand-subtle': themeConfig.token.colorPrimaryBg,
  '--hb-v2-info': themeConfig.token.colorInfo,
  '--hb-v2-info-text': themeConfig.token.colorPrimaryHover,
  '--hb-v2-info-soft': themeConfig.token.colorPrimaryBg,
  '--hb-v2-success': themeConfig.token.colorSuccess,
  '--hb-v2-success-text': hbSemanticTokens.successText,
  '--hb-v2-success-soft': hbSemanticTokens.successSoft,
  '--hb-v2-warning': themeConfig.token.colorWarning,
  '--hb-v2-warning-text': hbSemanticTokens.warningText,
  '--hb-v2-warning-border': hbSemanticTokens.warningBorder,
  '--hb-v2-warning-soft': hbSemanticTokens.warningSoft,
  '--hb-v2-error': themeConfig.token.colorError,
  '--hb-v2-error-text': hbSemanticTokens.errorText,
  '--hb-v2-error-soft': themeConfig.token.colorErrorBg,
  '--hb-v2-error-border': themeConfig.token.colorErrorBorder,
  '--hb-v2-focus-color': hbSemanticTokens.focusColor,
  '--hb-v2-focus': hbSemanticTokens.focusRing,
  '--hb-v2-shadow-control': themeConfig.components.Button.defaultShadow,
  '--hb-v2-shadow-primary': themeConfig.components.Button.primaryShadow,
  '--hb-v2-control-sm': px(themeConfig.token.controlHeightSM),
  '--hb-v2-control': px(themeConfig.token.controlHeight),
  '--hb-v2-control-lg': px(themeConfig.token.controlHeightLG),
  '--hb-grade-unrated-bg': hbSemanticTokens.unratedGrade.bg,
  '--hb-grade-unrated-fg': hbSemanticTokens.unratedGrade.fg,
  '--hb-grade-unrated-border': hbSemanticTokens.unratedGrade.border,
});

export function applyHbCssVariables(root = document.documentElement) {
  for (const [name, value] of Object.entries(HB_CSS_VARIABLES)) {
    root.style.setProperty(name, value);
  }
}

export const SABC_COLOR = hbSemanticTokens.grade;
export const SABC_UNRATED_COLOR = hbSemanticTokens.unratedGrade;
